# Generated by Django 5.0.7 on 2024-07-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='devtool',
        ),
    ]
