# Generated by Django 5.0.7 on 2024-07-17 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtools', '0001_initial'),
        ('ideas', '0002_remove_idea_devtool'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='devtool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devtools.devtool', verbose_name='개발툴'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, upload_to='ideas/%Y%m%d', verbose_name='이미지'),
        ),
    ]
