# Generated by Django 5.0.7 on 2024-07-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_idea_devtool_alter_idea_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='bookmark',
            field=models.BooleanField(default=False, verbose_name='북마크'),
        ),
    ]
