# Generated by Django 5.0.7 on 2024-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_alter_idea_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, upload_to='ideas/%Y%m%d', verbose_name='이미지'),
        ),
    ]
