# Generated by Django 5.0.7 on 2024-07-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movielog', '0002_review_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('Action', '액션'), ('Comedy', '코미디'), ('Drama', '드라마'), ('Sci-Fi', '공상과학'), ('Romance', '로맨스'), ('Thriller', '스릴러'), ('Horror', '공포'), ('Animation', '애니메이션'), ('Crime', '범죄'), ('Fantasy', '판타지'), ('Family', '가족'), ('Adventure', '모험'), ('War', '전쟁'), ('Music', '음악'), ('Documentary', '다큐멘터리'), ('Etc', '기타')], max_length=50),
        ),
    ]
